/* Admin page text (kept next to the admin code so data.ts stays about the public site). */
import type { L } from '../data';

export const at = {
  title: { ar: 'لوحة الإدارة | منصور قصقوص', en: 'Admin Dashboard | Mansour Qasqous' } as L,
  loginTitle: { ar: 'تسجيل الدخول إلى لوحة الإدارة', en: 'Sign in to the Admin Dashboard' } as L,
  email: { ar: 'البريد الإلكتروني', en: 'Email address' } as L,
  password: { ar: 'كلمة المرور', en: 'Password' } as L,
  signIn: { ar: 'تسجيل الدخول', en: 'Sign in' } as L,
  signingIn: { ar: 'جارٍ تسجيل الدخول...', en: 'Signing in...' } as L,
  badCreds: { ar: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.', en: 'The email address or password is incorrect.' } as L,
  tooMany: { ar: 'تم إجراء محاولات كثيرة. انتظر قليلًا ثم حاول مرة أخرى.', en: 'Too many attempts. Please wait a moment and try again.' } as L,
  network: { ar: 'تعذّر الاتصال بالخدمة. تحقق من اتصال الإنترنت ثم حاول مجددًا.', en: 'Unable to connect. Check your internet connection and try again.' } as L,
  expired: { ar: 'انتهت جلسة تسجيل الدخول. سجّل الدخول مرة أخرى للمتابعة.', en: 'Your session has expired. Please sign in again to continue.' } as L,
  notConfigured: {
    ar: 'إعداد Supabase غير مكتمل. أضف VITE_SUPABASE_URL وVITE_SUPABASE_ANON_KEY ثم أعد النشر.',
    en: 'Supabase configuration is incomplete. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY, then redeploy.',
  } as L,
  heading: { ar: 'صندوق الرسائل', en: 'Message Inbox' } as L,
  total: { ar: 'إجمالي الرسائل', en: 'Total Messages' } as L,
  unread: { ar: 'رسائل غير مقروءة', en: 'Unread Messages' } as L,
  all: { ar: 'جميع الرسائل', en: 'All Messages' } as L,
  refresh: { ar: 'تحديث الرسائل', en: 'Refresh' } as L,
  logout: { ar: 'تسجيل الخروج', en: 'Sign out' } as L,
  site: { ar: 'العودة إلى الموقع', en: 'View Website' } as L,
  loading: { ar: 'جارٍ تحميل الرسائل...', en: 'Loading messages...' } as L,
  loadErr: {
    ar: 'تعذّر تحميل الرسائل. تحقق من إعداد قاعدة البيانات وصلاحيات مستخدم الإدارة.',
    en: 'Unable to load messages. Check the database setup and admin-user permissions.',
  } as L,
  actErr: { ar: 'تعذّر تنفيذ العملية. حاول مرة أخرى.', en: 'The action could not be completed. Please try again.' } as L,
  empty: { ar: 'لا توجد رسائل حتى الآن.', en: 'No messages yet.' } as L,
  emptyUnread: { ar: 'لا توجد رسائل غير مقروءة.', en: 'No unread messages.' } as L,
  noSubject: { ar: '(بدون موضوع)', en: '(No subject)' } as L,
  reply: { ar: 'الرد عبر البريد', en: 'Reply by Email' } as L,
  markRead: { ar: 'تحديد كمقروءة', en: 'Mark as Read' } as L,
  markUnread: { ar: 'تحديد كغير مقروءة', en: 'Mark as Unread' } as L,
  del: { ar: 'حذف الرسالة', en: 'Delete' } as L,
  confirmDel: { ar: 'هل تريد حذف هذه الرسالة نهائيًا؟', en: 'Are you sure you want to permanently delete this message?' } as L,
};
